### ISSUE TITLE
Finalization of invalid IFEs and invalid IFEs without challenge aren't reported by the Watcher

### ISSUE THREAD

**Issue by pgebal** [omgnetwork/elixir-omg#671] opened 2019-05-07 15:52 UTC
User is not notified about finalized and processed in-flight exits from utxos that are not recognized in State, which means that funds on plasma might be compromised.

This might be done like in the case of standard exits, by producing an event.

**Comment by pdobacz** [comment] 2019-05-08 07:02
:+1: 

This relates to the issue/ticket to introduce the notion of late IFEs which when invalid, would lead to an `:unchallenged_exit` event, similar to standard exits. The old ticket was OMG-408.

Copying the notes over from there:

> Introduce the concept of "late invalid exit" for IFEs
> 
> These would be:
> 
> late non canonical IFE that are still treated as canonical
> late canonical IFEs that are still treated as non canonical (?)
> late invalid piggybacks
> They probably need the same treatement as SEs but really not sure. This requires careful reapproaching of the subject and, potentially, implementing functionality and tests similar to that of SEs.
> 
> Idea is still the same - give early warning that the status of exits is invalid on the root chain for too long (jeopardizing funds deposited)

**Comment by InoMurko** [comment] 2019-12-13 10:34
is this still relevant @pdobacz ?

**Comment by pdobacz** [comment] 2019-12-13 11:50
I'm afraid yes

**Comment by InoMurko** [comment] 2019-12-13 12:58
Cool, sounds like a mainnet blocker?

**Comment by pdobacz** [comment] 2019-12-13 13:31
Could be, but not sure. It's hard for me alone to decide that. 

Reiterating for anyone trying to discern this:

The issue is that IFEs, where there is something "invalid" about them and which go for too long without challenging, won't be reported as such to the watcher's user via `unchallenged_exit` event. "Something invalid about them" means that if they finalize, the child chain might be underfunded (byzantine).

**Comment by InoMurko** [comment] 2019-12-13 13:33
Ok. Do we have a way to address this?

**Comment by pdobacz** [comment] 2019-12-13 13:47
We're kinda "removing" the problem by doing prompt challenges of any invalidities around IFEs discovered, which is the happy-path (as far as invalid IFEs can be seen as happy). This is catered for already, as all the challenge-able conditions are reported.

> But otherwise it's the incentive mechanisms of those running the watcher that should sort the problem. Correct?

Not sure if this understanding is correct. This issue is about notifying (or current lack thereof) the Watcher users about a condition that should prompt them to mass exit. So in other words this is a rather detailed and paranoid measure of protecting funds and following protocol. SEs have this, IFEs don't.

**Comment by InoMurko** [comment] 2019-12-13 13:57
OK. So this when the title of the issue says ```... in-flight exit must be handled```
the handling means mass exit, correct?

What we currently offer in terms of notifying those that run Watchers is the API and configuration for Datadog (that currently does not export events, but will). That should be enough for now. cc @achiurizo @kasima 


@pdobacz pls correct me if I'm wrong.

**Comment by pdobacz** [comment] 2019-12-13 15:03
> OK. So this when the title of the issue says `... in-flight exit must be handled`
the handling means mass exit, correct?

um, with the ellipsis you made there, I'm not 100% sure we're on the same page. So let's clarify: the title says `Invalid utxo exit ... must be handled` and only goes on to specify, that it it is a utxo exit stemming from IFE finalizing that we're concerned about. 

The issue is about handling of a specific byzantine condition. The handling is done by the Watcher notifying the user, which is currently **absent** for this condition, for IFEs. 

User's reaction to this notification would be a mass exit, but that's not part of "handling" in this sense; that's user's responsibility to follow-up with an action, after being notified.

I'm wondering where our confusion could be coming from (if there's one). Lemme try to rephrase the title to a more user-centric description

**Comment by InoMurko** [comment] 2019-12-18 16:41
PS: Get `product` input. cc @achiurizo

**Comment by pdobacz** [comment] 2020-02-07 10:40
this must be solved with #1275 in mind, which proposes, as one of possible solutions, the introduction of an explicit `invalidly_processed_exit` event family.

Then, doing "invalid IFEs and invalid IFEs without challenge" must be done in line with this.

**Comment by pdobacz** [comment] 2020-03-10 14:43
Contingent on #1318 being done as the description suggests, the continuation of that list to fix this issue here is: 
8. [ ] Throw away the "inactive on recognition" and the getting of exit structs for IFEs
9. [ ] Cabbagize invalid IFE tests and add tests, where a Watcher is resynced (from clear state).
10. [ ] implement proper exit statuses for IFEs, taking `invalidly_processed_exit` approach (see #1318 for the proposition of those statuses)
11. [ ] implement late and invalidly processed IFEs and piggybacks

**Comment by pnowosie** [comment] 2020-07-16 12:56
Honestly I cannot put myself into this issue. Issue is old enough that same statements seems to be false, e.g:
- lack of emitting [`unchallenge_exit` event for IFE](https://github.com/omgnetwork/elixir-omg/blob/652023025f0cc53370e77802af5659c72eab0592/docs/api_specs/status_events_specs.md#unchallenged_non_canonical_ife)
- lack of emmiting [`invalid piggypack` event](https://github.com/omgnetwork/elixir-omg/blob/652023025f0cc53370e77802af5659c72eab0592/docs/api_specs/status_events_specs.md#invalid_piggyback)
It proposes to split `unchallenge exit` into two events `unchallenge exit` and `invalidly processed exit` as described in #1318.
#1318 mentions branch [pdobacz/1318_invalidly_processed](https://github.com/omgnetwork/elixir-omg/tree/pdobacz/1318_invalidly_processed) which points to `master` now :open_hands: 

It might be beneficial to have the events splitted - however I can't see the gain when `unchallenged_exit` means game-over :checkered_flag: and mass exit :thinking: 

@thec00n @boolafish @kevsul - maybe you could be able to put some light on it?

**Comment by boolafish** [comment] 2020-07-27 02:32
Let's close this, with unchallenge exit event, it should have cover the concern of the title: "Finalization of invalid IFEs and invalid IFEs without challenge aren't reported by the Watcher" though in an not obvious way.

However, I do think the proposal of the part of `Proper exit statuses` in  #1318 is great. That is a way better reflection of the system exit status. Please keep that being tracked.

**Closed by boolafish** 2020-07-27 02:32 UTC
Labels: martini
