### ISSUE TITLE
Clean up perf to be able to run against env

### ISSUE THREAD

**Issue by kevsul** [omgnetwork/elixir-omg#1600] opened 2020-06-22 13:56 UTC

**Comment by boolafish** [comment] 2020-08-19 08:33
Note that @ayrat555 has been working on this as part of https://github.com/omgnetwork/childchain/issues/59

One PR: https://github.com/omgnetwork/elixir-omg/pull/1691

**Comment by boolafish** [comment] 2020-08-31 07:45
Hihi @Ayrat Badykov, I am sorry to be that person, but can I ask more on the PR: https://github.com/omgnetwork/elixir-omg/pull/1691 My main concern is what and why we are maintaining as @Ino pointed out.

After the PR, it seems like only 2 main suite of tests are left: “byzantine” and “extended perf test”. I believe extended perf test is already replaceable via the childchain tests or the utxo test in original perf setup. (It is sending a bunch of tx to childchain server directly right?). I think it is quite fair and remove that. (cc. @kevin please help double check on this point)

The thing perf does not have is testing with multiple exits, and we previously had an incident that our service was actually poor at handling multiple exit events. So it probably makes sense to have tests that auto spins up certain spike amount of exits. But I would strongly recommend to port that using the same style of perf original setup where it hit the env instead of relying on docker geth accounts.

I recall @kevsul had been working on this previously, what was your latest status, is there any work that can be reusable??

**Comment by boolafish** [comment] 2020-08-31 07:46
I am reopening this. @ayrat555 if this is too much to ask to cleanup I think it is fine and fair to keep the remaining to gold team but I will leave this decision to you.

**Comment by InoMurko** [comment] 2020-08-31 07:49
Perhaps it makes sense to open a new issue with the new requirements, rather than opening this one?

**Comment by kevsul** [comment] 2020-08-31 09:37
Yeah, the original purpose of this issue was to port only the byzantine_events_test into the Chaperon perf test framework. 
The extended_perftest had already been moved over. We purposefully don't use any of the geth specific stuff, such as `generate_user()` with the load tests because they have to run against remote nodes e.g. the stress env.

Apologies for not catching this sooner @ayrat555 , I didn't get around to looking at the PR until today.

I did make a start on this a while back, but I didn't get half as far.

I think we can build on @ayrat555's work though -  we just need to run the tests via the Chaperon framework.
We want to test the system under load of many exits, so I guess we need scenarios for:

1. Starting a valid exit
2. Starting an invalid exit
3. Challenging an invalid exit

(similarly for IFEs, but let's leave that as a separate task)

**Comment by InoMurko** [comment] 2020-08-31 11:05
I would say that @ayrat555 did what the ticket says it should be done. There's no mention of Chaperon. The PR he did decoupled those tests with the elixir-omg code, which is great. We either rename this ticket so that the requirement is chaperon of newly added tests, or close this one and open a new one.

**Comment by boolafish** [comment] 2020-08-31 11:14
That was the unfortunate part as the description of the issue is empty😂😂so everyone are not in the same page on what the requirements should be.

I still want to give big 👏👏to @ayrat555 as that it was the ball that everyone is throwing or waiting some brave guy to take😛

To move forward I just want to make sure it is still tracked, no preference in what form

**Closed** 2020-09-18 14:02 UTC
