### ISSUE TITLE
`transaction.create` doesn't deduct fee from `outputs`

### ISSUE THREAD

**Issue by ripzery** [omgnetwork/elixir-omg#1761] opened 2020-11-02 06:38 UTC
Example response:

```
{
  "data": {
    "result": "complete",
    "transactions": [
      {
        "fee": {
          "amount": 1,
          "currency": "0x0000000000000000000000000000000000000000"
        },
        "inputs": [
          {
            "amount": 49910000000000000,
            "blknum": 138000,
            "creating_txhash": "0xf9b02554e85ed7ed291c0a7657519d38de7ec2660db1e7e5bb0b8f0b435c0fc4",
            "currency": "0x0000000000000000000000000000000000000000",
            "inserted_at": "2020-10-29T14:20:53Z",
            "oindex": 1,
            "otype": 1,
            "owner": "0x31bc9ea3093d5a4faeff8fdf24499cea3f7c1f92",
            "spending_txhash": null,
            "txindex": 0,
            "updated_at": "2020-10-29T14:20:53Z",
            "utxo_pos": 138000000000001
          },
          {
            "amount": 3000,
            "blknum": 142000,
            "creating_txhash": "0x8fe5f64976fdca50c15bd6d6a1b9aa473227b5d5650dc2136a8f5fceb5d0b75a",
            "currency": "0xd5b83b1fdbc00bfe3679a60b2cb6252418df0d99",
            "inserted_at": "2020-10-29T14:58:36Z",
            "oindex": 0,
            "otype": 1,
            "owner": "0x31bc9ea3093d5a4faeff8fdf24499cea3f7c1f92",
            "spending_txhash": null,
            "txindex": 0,
            "updated_at": "2020-10-29T14:58:36Z",
            "utxo_pos": 142000000000000
          }
        ],
        "metadata": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "outputs": [
          {
            "amount": 700,
            "currency": "0xd5b83b1fdbc00bfe3679a60b2cb6252418df0d99",
            "owner": "0xbdba40131ec2d16f067cc242644ea69e8afd0d4a"
          },
          {
            "amount": 49910000000000000,
            "currency": "0x0000000000000000000000000000000000000000",
            "owner": "0x31bc9ea3093d5a4faeff8fdf24499cea3f7c1f92"
          },
          {
            "amount": 2300,
            "currency": "0xd5b83b1fdbc00bfe3679a60b2cb6252418df0d99",
            "owner": "0x31bc9ea3093d5a4faeff8fdf24499cea3f7c1f92"
          }
        ],
        "sign_hash": "0x6f8a85fee13ab63fdb319537e3ff8b068875b85d3f2b01f5e92f5e8b729f3656",
        "txbytes": "0xf8fe01f842a000000000000000000000000000000000000000000000000000007d82a0faa001a000000000000000000000000000000000000000000000000000008125f38ee000f895ef01ed94bdba40131ec2d16f067cc242644ea69e8afd0d4a94d5b83b1fdbc00bfe3679a60b2cb6252418df0d998202bcf401f29431bc9ea3093d5a4faeff8fdf24499cea3f7c1f9294000000000000000000000000000000000000000087b150e16cbd5fffef01ed9431bc9ea3093d5a4faeff8fdf24499cea3f7c1f9294d5b83b1fdbc00bfe3679a60b2cb6252418df0d998208fc80a00000000000000000000000000000000000000000000000000000000000000000",
        "typed_data": {
          "domain": {
            "name": "OMG Network",
            "salt": "0xfad5c7f626d80f9256ef01929f3beb96e058b8b4b0e3fe52d84f054c0e2a7a83",
            "verifyingContract": "0xb43f53394d86deab35bc2d8356d6522ced6429b5",
            "version": "1"
          },
          "message": {
            "input0": {
              "blknum": 138000,
              "oindex": 1,
              "txindex": 0
            },
            "input1": {
              "blknum": 142000,
              "oindex": 0,
              "txindex": 0
            },
            "input2": {
              "blknum": 0,
              "oindex": 0,
              "txindex": 0
            },
            "input3": {
              "blknum": 0,
              "oindex": 0,
              "txindex": 0
            },
            "metadata": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "output0": {
              "amount": 700,
              "currency": "0xd5b83b1fdbc00bfe3679a60b2cb6252418df0d99",
              "owner": "0xbdba40131ec2d16f067cc242644ea69e8afd0d4a"
            },
            "output1": {
              "amount": 49910000000000000,
              "currency": "0x0000000000000000000000000000000000000000",
              "owner": "0x31bc9ea3093d5a4faeff8fdf24499cea3f7c1f92"
            },
            "output2": {
              "amount": 2300,
              "currency": "0xd5b83b1fdbc00bfe3679a60b2cb6252418df0d99",
              "owner": "0x31bc9ea3093d5a4faeff8fdf24499cea3f7c1f92"
            },
            "output3": {
              "amount": 0,
              "currency": "0x0000000000000000000000000000000000000000",
              "owner": "0x0000000000000000000000000000000000000000"
            }
          },
          "primaryType": "Transaction",
          "types": {
            "EIP712Domain": [
              {
                "name": "name",
                "type": "string"
              },
              {
                "name": "version",
                "type": "string"
              },
              {
                "name": "verifyingContract",
                "type": "address"
              },
              {
                "name": "salt",
                "type": "bytes32"
              }
            ],
            "Input": [
              {
                "name": "blknum",
                "type": "uint256"
              },
              {
                "name": "txindex",
                "type": "uint256"
              },
              {
                "name": "oindex",
                "type": "uint256"
              }
            ],
            "Output": [
              {
                "name": "outputType",
                "type": "uint256"
              },
              {
                "name": "outputGuard",
                "type": "bytes20"
              },
              {
                "name": "currency",
                "type": "address"
              },
              {
                "name": "amount",
                "type": "uint256"
              }
            ],
            "Transaction": [
              {
                "name": "txType",
                "type": "uint256"
              },
              {
                "name": "input0",
                "type": "Input"
              },
              {
                "name": "input1",
                "type": "Input"
              },
              {
                "name": "input2",
                "type": "Input"
              },
              {
                "name": "input3",
                "type": "Input"
              },
              {
                "name": "output0",
                "type": "Output"
              },
              {
                "name": "output1",
                "type": "Output"
              },
              {
                "name": "output2",
                "type": "Output"
              },
              {
                "name": "output3",
                "type": "Output"
              },
              {
                "name": "txData",
                "type": "uint256"
              },
              {
                "name": "metadata",
                "type": "bytes32"
              }
            ]
          }
        }
      }
    ]
  },
  "service_name": "watcher_info",
  "success": true,
  "version": "1.0.5+54305bb"
}
```

**Comment by okalouti** [comment] 2020-11-02 10:57
Alright, so if you look at [this](https://github.com/omgnetwork/elixir-omg/blob/251cfc00b81f06086210f520a2b2ca527df7623f/apps/omg_watcher_info/lib/omg_watcher_info/transaction.ex#L199) function that builds a transaction’s outputs, you see that the fee is passed in along with the payments for the derivation of the “change” amount. So the “change” output takes into account the fee.  If you look at the test suite, the deduction of the fees is also clearly covered in multiple tests (see : [here](https://github.com/omgnetwork/elixir-omg/blob/251cfc00b81f06086210f520a2b2ca527df7623f/apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/transaction_test.exs#L1233-L1624). – it’s not explicit but you can conclude with some simple arithmetic) (edited)

**Comment by okalouti** [comment] 2020-11-02 11:02
Call to https://watcher-info.rinkeby.v1.omg.network/transaction.create with OMG fee: 

Request Parameters: 
```json 
{
  "fee" : {"currency": "0x942f123b3587ede66193aa52cf2bf9264c564f87"},
  "owner":  "0x8cb0de6206f459812525f2ba043b14155c2230c0",
  "payments": [
    {
      "amount": 30,
      "currency": "0x0000000000000000000000000000000000000000",
      "owner": "0xc139e1d7358e4faf76f0fcf792255016af5dc742"
    }
  ]	
}
```

Response:

```json
...
 "inputs": [
          {
            "amount": 99970000000000000,
            "blknum": 144000,
            "creating_txhash": "0x206d1e58aab14f339bfa03b54b39e9c6cb0cb6c912823ae38fcbadb04266d6b8",
            "currency": "0x0000000000000000000000000000000000000000",
            "inserted_at": "2020-10-29T19:59:19Z",
            "oindex": 1,
            "otype": 1,
            "owner": "0x8cb0de6206f459812525f2ba043b14155c2230c0",
            "spending_txhash": null,
            "txindex": 0,
            "updated_at": "2020-10-29T19:59:19Z",
            "utxo_pos": 144000000000001
          },
          {
            "amount": 100000000000000000000,
            "blknum": 176000,
            "creating_txhash": "0x879ecb82e49904152adac6764546177be666cedc42421f29c87f4e129c769bf6",
            "currency": "0x942f123b3587ede66193aa52cf2bf9264c564f87",
            "inserted_at": "2020-11-01T21:40:05Z",
            "oindex": 1,
            "otype": 1,
            "owner": "0x8cb0de6206f459812525f2ba043b14155c2230c0",
            "spending_txhash": null,
            "txindex": 0,
            "updated_at": "2020-11-01T21:40:05Z",
            "utxo_pos": 176000000000001
          }
        ],
        "metadata": null,
        "outputs": [
          {
            "amount": 1,
            "currency": "0x0000000000000000000000000000000000000000",
            "owner": "0xc139e1d7358e4faf76f0fcf792255016af5dc742"
          },
          {
            "amount": 99969999999999999,
            "currency": "0x0000000000000000000000000000000000000000",
            "owner": "0x8cb0de6206f459812525f2ba043b14155c2230c0"
          },
          {
            "amount": 99998254594020039393,
            "currency": "0x942f123b3587ede66193aa52cf2bf9264c564f87",
            "owner": "0x8cb0de6206f459812525f2ba043b14155c2230c0"
          }
        ]
...
```

**Comment by okalouti** [comment] 2020-11-02 11:02
The fee is clearly being deducted in the fee output.

**Comment by okalouti** [comment] 2020-11-02 11:09
Above call was made with the same address as the inputs owner in the issue: `"0x31bc9ea3093d5a4faeff8fdf24499cea3f7c1f92"`

**Comment by nicholasmueller** [comment] 2020-11-04 10:00
closing as this is indeed not a bug in the watcher but an implementation detail in the clients environment. (big number rounding)

**Closed by nicholasmueller** 2020-11-04 10:00 UTC
Labels: bug
